networks:
  hadoop:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    restart: always
    environment:
      - CLUSTER_NAME=hdfs-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./host_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode1
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./host_datanode1:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode2
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./host_datanode2:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  datanode3:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode3
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./host_datanode3:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode